{% set name = "django-sequences" %}
{% set version = "2.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 91f4b222ac8fc102ae76abef76ff1291684b4dec0d38d97f189b64b26c2a1b56

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry
  run:
    - django >=3.2
    - python >={{ python_min }}

test:
  imports:
    - sequences
    - sequences.migrations
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/aaugustin/django-sequences
  summary: Generate gapless sequences of integer values.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MichelML
